### ISSUE TITLE
getUserJars API changed in Spark 2.2.1

### ISSUE THREAD

**Issue by parente** [Valassis-Digital-Media/spylon-kernel#43]
No longer accepts a boolean and no longer includes the YARN JARs.

https://github.com/apache/spark/commit/d10c9dc3f631a26dbbbd8f5c601ca2001a5d7c80

```
py4j.protocol.Py4JError: An error occurred while calling z:org.apache.spark.util.Utils.getUserJars. Trace:
py4j.Py4JException: Method getUserJars([class org.apache.spark.SparkConf, class java.lang.Boolean]) does not exist
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
        at py4j.Gateway.invoke(Gateway.java:274)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
```

I think it's OK to try/except around the newer API call then fall back on the old one.

**Comment by parente** [comment]
Make that `getLocalUserJarsForShell`.
